apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
  labels:
    app: web-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:
        - name: web-server
          image: web-server
          imagePullPolicy: Always
          env:
            - name: GRPC_SERVER_HOST
              value: grpc-server
            - name: GRPC_SERVER_PORT
              value: "8090"
          ports:
            - name: http
              containerPort: 9000
              protocol: TCP
          resources:
            {}
